<?php

use Illuminate\Database\Seeder;

class TrainingResourcesTableSeeder extends Seeder {

	/**
	 * Auto generated seed file
	 *
	 * @return void
	 */
	public function run()
	{
		# Warning! The next line will delete all entries from the table.
		\DB::table('training_resources')->delete();

		$dateTime = Carbon\Carbon::now();
		
		# This will insert data to the table
		\DB::table('training_resources')->insert(array (
			0 => 
			array (
				'id' => '1',
				'name' => 'Formació Inicial',
				'short_name' => 'form_ini',
				'description' => 'L\'objectiu principal de la Formació Inicial és oferir una formació pedagògica bàsica, eminentment pràctica, coherent amb el model educatiu europeu i que permeti al professorat el desenvolupament, millora i/o innovació de la seva actuació docent.',
				'thumbnail' => 'images/logo_formacio_inicial.png',
				'external_url' => '',
				'parent_id' => NULL,
				'lft' => '1',
				'rgt' => '150',
				'depth' => '0',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			1 => 
			array (
				'id' => '2',
				'name' => 'Formació Continua',
				'short_name' => 'form_cont',
				'description' => 'Cicles Formatius de Grau Superior disponibles a l\'Institut de l\'Ebre',
				'thumbnail' => 'images/logo_formacio_continua.png',
				'external_url' => '',
				'parent_id' => NULL,
				'lft' => '151',
				'rgt' => '156',
				'depth' => '0',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			2 => 
			array (
				'id' => '3',
				'name' => 'Formació Ocupacional',
				'short_name' => 'admin_fin',
				'description' => 'Cicles Formatius de Grau Mitjà',
				'thumbnail' => 'images/logo_formacio_ocupacional.png',
				'external_url' => '',
				'parent_id' => NULL,
				'lft' => '157',
				'rgt' => '160',
				'depth' => '0',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			3 => 
			array (
				'id' => '4',
				'name' => 'Altres Formacions',
				'short_name' => 'altres_formacions',
				'description' => 'Superque poterunt aliasque cognitum cum vel tractant importat. Sensibus ideamque tollatur fas quisquis sub non meo. Ne to habeat animam cuncta at figere ei animum. At ea ingens et plures vocant mandat optime carnem. Effectus formalem videntur est ostensum',
				'thumbnail' => 'images/logo_altres_formacions.png',
				'external_url' => '',
				'parent_id' => NULL,
				'lft' => '161',
				'rgt' => '168',
				'depth' => '0',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			4 => 
			array (
				'id' => '5',
				'name' => 'Administració i finances',
				'short_name' => 'admin_fin',
				'description' => 'Cicles Formatius de Grau Mitjà',
				'thumbnail' => 'images/Logo_03_admin_fin.png',
				'external_url' => 'http://www.iesebre.com/index.php/2011-10-28-13-41-40/cfgm',
				'parent_id' => '20',
				'lft' => '3',
				'rgt' => '6',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			5 => 
			array (
				'id' => '6',
			'name' => 'Gestió administrativa (LOE)',
				'short_name' => 'ges_admin',
				'description' => 'Cicle Formatiu de Grau Mitjà',
				'thumbnail' => 'images/Logo_03_admin_fin.png',
				'external_url' => 'http://www.iesebre.com/index.php/2011-10-28-13-41-40/cfgm',
				'parent_id' => '5',
				'lft' => '4',
				'rgt' => '5',
				'depth' => '3',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			6 => 
			array (
				'id' => '7',
				'name' => 'Sanitat',
				'short_name' => 'sanitat',
				'description' => 'Cicles Formatius de Grau Mitjà',
				'thumbnail' => 'images/logo_09_sanitat.png',
				'external_url' => 'http://www.iesebre.com/index.php/2011-10-28-13-41-40/cfgm',
				'parent_id' => '20',
				'lft' => '7',
				'rgt' => '14',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			7 => 
			array (
				'id' => '8',
			'name' => 'Cures auxiliars d\'infermeria (LOGSE)',
				'short_name' => 'aux_infermeria',
				'description' => 'Cicle Formatiu de Grau Mitjà',
				'thumbnail' => 'images/logo_09_sanitat.png',
				'external_url' => 'http://www.iesebre.com/index.php/2011-10-28-13-41-40/cfgm',
				'parent_id' => '7',
				'lft' => '8',
				'rgt' => '9',
				'depth' => '3',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			8 => 
			array (
				'id' => '9',
			'name' => 'Emergències sanitàries (LOE)',
				'short_name' => 'emerg_sanitaries',
				'description' => 'Cicle Formatiu de Grau Mitjà',
				'thumbnail' => 'images/logo_09_sanitat.png',
				'external_url' => 'http://www.iesebre.com/index.php/2011-10-28-13-41-40/cfgm',
				'parent_id' => '7',
				'lft' => '10',
				'rgt' => '11',
				'depth' => '3',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			9 => 
			array (
				'id' => '10',
			'name' => 'Farmàcia i parafarmàcia (LOE)',
				'short_name' => 'farmacia_parafarmacia',
				'description' => 'Cicle Formatiu de Grau Mitjà',
				'thumbnail' => 'images/logo_09_sanitat.png',
				'external_url' => 'http://www.iesebre.com/index.php/2011-10-28-13-41-40/cfgm',
				'parent_id' => '7',
				'lft' => '12',
				'rgt' => '13',
				'depth' => '3',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			10 => 
			array (
				'id' => '11',
				'name' => 'Fabricació mecànica',
				'short_name' => 'fabricacio_mecanica',
				'description' => 'Cicles Formatius de Grau Mitjà',
				'thumbnail' => 'images/logo_06 _mecanica.png',
				'external_url' => 'http://www.iesebre.com/index.php/2011-10-28-13-41-40/cfgm',
				'parent_id' => '20',
				'lft' => '15',
				'rgt' => '20',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			11 => 
			array (
				'id' => '12',
			'name' => 'Mecanització (LOE)',
				'short_name' => 'mecanitzacio',
				'description' => 'Cicle Formatiu de Grau Mitjà',
				'thumbnail' => 'images/logo_06 _mecanica.png',
				'external_url' => 'http://www.iesebre.com/index.php/2011-10-28-13-41-40/cfgm',
				'parent_id' => '11',
				'lft' => '16',
				'rgt' => '17',
				'depth' => '3',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			12 => 
			array (
				'id' => '13',
			'name' => 'Soldadura i caldereria (LOE)',
				'short_name' => 'soldadura_caldereria',
				'description' => 'Cicle Formatiu de Grau Mitjà',
				'thumbnail' => 'images/logo_06 _mecanica.png',
				'external_url' => 'http://www.iesebre.com/index.php/2011-10-28-13-41-40/cfgm',
				'parent_id' => '11',
				'lft' => '18',
				'rgt' => '19',
				'depth' => '3',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			13 => 
			array (
				'id' => '14',
				'name' => 'Administració i gestió',
				'short_name' => 'admin_gestio',
				'description' => 'Cicles Formatius de Grau Superior',
				'thumbnail' => 'images/Logo_03_admin_fin.png',
				'external_url' => 'http://www.iesebre.com/index.php/2011-10-28-13-41-40/cfgs',
				'parent_id' => '20',
				'lft' => '21',
				'rgt' => '26',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			14 => 
			array (
				'id' => '15',
			'name' => 'Administració i finances (LOE)',
				'short_name' => 'admin_finances',
				'description' => 'Cicle Formatiu de Grau Superior',
				'thumbnail' => 'images/Logo_03_admin_fin.png',
				'external_url' => 'http://www.iesebre.com/index.php/2011-10-28-13-41-40/cfgs',
				'parent_id' => '14',
				'lft' => '22',
				'rgt' => '23',
				'depth' => '3',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			15 => 
			array (
				'id' => '16',
			'name' => 'Assistència a la direcció (LOE)',
				'short_name' => 'assistencia_direccio',
				'description' => 'Cicle Formatiu de Grau Superior',
				'thumbnail' => 'images/Logo_03_admin_fin.png',
				'external_url' => 'http://www.iesebre.com/index.php/2011-10-28-13-41-40/cfgs',
				'parent_id' => '14',
				'lft' => '24',
				'rgt' => '25',
				'depth' => '3',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			16 => 
			array (
				'id' => '17',
				'name' => 'Informàtica',
				'short_name' => 'informatica',
				'description' => 'Cicles Formatius de Grau Superior',
				'thumbnail' => 'images/logo_07_informatica.png',
				'external_url' => 'http://www.iesebre.com/index.php/2011-10-28-13-41-40/cfgs',
				'parent_id' => '20',
				'lft' => '27',
				'rgt' => '32',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			17 => 
			array (
				'id' => '18',
			'name' => 'Administració de sistemes informàtics en la xarxa (LOE)',
				'short_name' => 'ASIX',
				'description' => 'Cicle Formatiu de Grau Superior',
				'thumbnail' => 'images/logo_07_informatica.png',
				'external_url' => 'http://www.iesebre.com/index.php/2011-10-28-13-41-40/cfgs',
				'parent_id' => '17',
				'lft' => '28',
				'rgt' => '29',
				'depth' => '3',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			18 => 
			array (
				'id' => '19',
			'name' => 'Desenvolupament d\'aplicacions multiplataforma (LOE)',
				'short_name' => 'DAM',
				'description' => 'Cicle Formatiu de Grau Superior',
				'thumbnail' => 'images/logo_07_informatica.png',
				'external_url' => 'http://www.iesebre.com/index.php/2011-10-28-13-41-40/cfgs',
				'parent_id' => '17',
				'lft' => '30',
				'rgt' => '31',
				'depth' => '3',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			19 => 
			array (
				'id' => '20',
				'name' => 'Institut de l\'Ebre',
				'short_name' => 'ies_ebre',
				'description' => 'El centre, ubicat al barri de Ferreries de Tortosa, va ser fundat l\'any 1928 amb el nom de "Centro de Formación Técnico Industrial" i és un del més antics de Catalunya.',
				'thumbnail' => 'images/ies_ebre.png',
				'external_url' => 'http://www.iesebre.com/',
				'parent_id' => '1',
				'lft' => '2',
				'rgt' => '43',
				'depth' => '1',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			20 => 
			array (
				'id' => '21',
				'name' => 'USOC',
				'short_name' => 'usoc',
				'description' => 'Fruebatur ha ut cupientem ingeniosi re inscitiae ac formantur. Ex re quomodo punctum ignotae quisnam de ii. Quem at quod du quam suam modo de solo. Societati at de ea persuasus dubitarem. Invenit majorem quiddam ad et at ac. Dissimilem ne ei ad utilitatis',
				'thumbnail' => 'images/logo_usoc.jpg',
				'external_url' => 'http://www.serveis.usoc.cat/',
				'parent_id' => '2',
				'lft' => '152',
				'rgt' => '153',
				'depth' => '1',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			21 => 
			array (
				'id' => '22',
				'name' => 'CAMBRA OFICIAL DE COMERÇ, INDÚSTRIA I NAVEGACIÓ DE TORTOSA',
				'short_name' => 'cambra_oficial',
				'description' => 'Formació contínua, formació ocupacional, formació subvencionada',
				'thumbnail' => 'images/logo_cambra_comerc_tortosa.jpg',
				'external_url' => 'http://www.cambratortosa.com/formacio/index.asp',
				'parent_id' => '2',
				'lft' => '154',
				'rgt' => '155',
				'depth' => '1',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			22 => 
			array (
				'id' => '23',
				'name' => 'ESCOLA DE L\'ESPLAI DE TORTOSA',
				'short_name' => 'escola_espai',
				'description' => 'Fruebatur ha ut cupientem ingeniosi re inscitiae ac formantur. Ex re quomodo punctum ignotae quisnam de ii. Quem at quod du quam suam modo de solo. Societati at de ea persuasus dubitarem. Invenit majorem quiddam ad et at ac. Dissimilem ne ei ad utilitatis',
				'thumbnail' => 'images/2_wkB9dV.png',
				'external_url' => 'http://www.escolaesplai.cat/',
				'parent_id' => '4',
				'lft' => '162',
				'rgt' => '163',
				'depth' => '1',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			23 => 
			array (
				'id' => '24',
				'name' => 'CFO Ajuntament de Tortosa',
				'short_name' => 'CFOAT',
				'description' => 'Superque poterunt aliasque cognitum cum vel tractant importat. Sensibus ideamque tollatur fas quisquis sub non meo. Ne to habeat animam cuncta at figere ei animum. At ea ingens et plures vocant mandat optime carnem. Effectus formalem videntur est ostensum',
				'thumbnail' => 'images/logo_tort.png',
				'external_url' => 'http://www.tortosa.cat/webajt/cfo/index.asp',
				'parent_id' => '4',
				'lft' => '164',
				'rgt' => '165',
				'depth' => '1',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			24 => 
			array (
				'id' => '25',
				'name' => 'AECE',
				'short_name' => 'aece',
				'description' => 'Superque poterunt aliasque cognitum cum vel tractant importat. Sensibus ideamque tollatur fas quisquis sub non meo. Ne to habeat animam cuncta at figere ei animum. At ea ingens et plures vocant mandat optime carnem. Effectus formalem videntur est ostensum',
				'thumbnail' => 'images/default_thumbnail.png',
				'external_url' => 'http://www.aecebre.org/',
				'parent_id' => '4',
				'lft' => '166',
				'rgt' => '167',
				'depth' => '1',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			25 => 
			array (
				'id' => '26',
				'name' => 'Institut Joaquín Bau',
				'short_name' => 'bau',
				'description' => 'El primer Institut fou fundat el 1844 i instal·lat a l’edifici del Seminari al carrer Montcada. Aquest edifici fou arrabassat als jesuïtes el 1767 després de la seva expulsió i desamortitzat el 1841. El 1848 es va haver de tancar per manca d’alumnat.',
				'thumbnail' => 'images/LOGOBAU2.png',
				'external_url' => 'http://agora.xtec.cat/iesjbau/projecte-educatiu/estudis/',
				'parent_id' => '1',
				'lft' => '44',
				'rgt' => '49',
				'depth' => '1',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			26 => 
			array (
				'id' => '27',
				'name' => 'UGT-IDFO',
				'short_name' => 'ugt',
				'description' => 'Superque poterunt aliasque cognitum cum vel tractant importat. Sensibus ideamque tollatur fas quisquis sub non meo. Ne to habeat animam cuncta at figere ei animum. At ea ingens et plures vocant mandat optime carnem. Effectus formalem videntur est ostensum',
				'thumbnail' => 'images/logo_idfo_ugt.png',
				'external_url' => 'http://www.idfo.com/',
				'parent_id' => '3',
				'lft' => '158',
				'rgt' => '159',
				'depth' => '1',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			27 => 
			array (
				'id' => '28',
				'name' => 'Edificació i obra civil',
				'short_name' => 'edificacio',
				'description' => 'Cicles Formatius de Grau Superior',
				'thumbnail' => 'images/logo_04_edificacio.png',
				'external_url' => 'http://www.iesebre.com/index.php/2011-10-28-13-41-40/cfgs',
				'parent_id' => '20',
				'lft' => '33',
				'rgt' => '36',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			28 => 
			array (
				'id' => '29',
			'name' => 'Projectes d\'edificació (LOE)',
				'short_name' => 'ASIX',
				'description' => 'Cicle Formatiu de Grau Superior',
				'thumbnail' => 'images/logo_04_edificacio.png',
				'external_url' => 'http://www.iesebre.com/index.php/2011-10-28-13-41-40/cfgs',
				'parent_id' => '28',
				'lft' => '34',
				'rgt' => '35',
				'depth' => '3',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			29 => 
			array (
				'id' => '30',
				'name' => 'Serveis socioculturals i a la comunitat',
				'short_name' => 'sociocultural',
				'description' => 'Cicles Formatius de Grau Superior',
				'thumbnail' => 'images/logo_10_sociocultural.png',
				'external_url' => 'http://www.iesebre.com/index.php/2011-10-28-13-41-40/cfgs',
				'parent_id' => '20',
				'lft' => '37',
				'rgt' => '42',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			30 => 
			array (
				'id' => '31',
			'name' => 'Integració social (LOGSE)',
				'short_name' => 'integracio_social',
				'description' => 'Cicle Formatiu de Grau Superior',
				'thumbnail' => 'images/logo_10_sociocultural.png',
				'external_url' => 'http://www.iesebre.com/index.php/2011-10-28-13-41-40/cfgs',
				'parent_id' => '30',
				'lft' => '38',
				'rgt' => '39',
				'depth' => '3',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			31 => 
			array (
				'id' => '32',
			'name' => 'Educació infantil (LOE)',
				'short_name' => 'integracio_infantil',
				'description' => 'Cicle Formatiu de Grau Superior',
				'thumbnail' => 'images/logo_10_sociocultural.png',
				'external_url' => 'http://www.iesebre.com/index.php/2011-10-28-13-41-40/cfgs',
				'parent_id' => '30',
				'lft' => '40',
				'rgt' => '41',
				'depth' => '3',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			32 => 
			array (
				'id' => '33',
				'name' => 'Institut Sól de Riu',
				'short_name' => 'sol_de_riu',
				'description' => 'L’Institut Sòl-de-Riu és un centre d’ensenyaments secundaris de titularitat pública depenent del Departament d’Ensenyament de la Generalitat de Catalunya. El nostre centre es troba a Alcanar, municipi situat a l’extrem més meridional de Catalunya a la com',
				'thumbnail' => 'images/sol_de_riu_400x400.png',
				'external_url' => 'http://institutsolderiu.cat/centre/estudis/fp/',
				'parent_id' => '1',
				'lft' => '50',
				'rgt' => '55',
				'depth' => '1',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			33 => 
			array (
				'id' => '34',
				'name' => 'Ins. Mare de Déu de la Candelera',
				'short_name' => 'mare_de_deu_de_la_candelera',
			'description' => 'L\'Institut Mare de Déu de la Candelera de l’Ametlla de mar és un centre públic d\'Educació Secundària on es poden cursar els estudis obligatoris (ESO) i els postobligatoris (BATXILLERAT i CICLES FORMATIUS). Al centre es rep un servei educatiu integral i in',
				'thumbnail' => 'images/mare_de_deu_de_la_candelera.gif',
				'external_url' => 'http://www.xtec.cat/centres/e3006976/INS/cicles_formatius.html',
				'parent_id' => '1',
				'lft' => '56',
				'rgt' => '59',
				'depth' => '1',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			34 => 
			array (
				'id' => '35',
				'name' => 'Institut Escola de Capacitació Nauticopesquera de Catalunya',
				'short_name' => 'iesnautica',
				'description' => 'Institut Escola de Capacitació Nauticopesquera de Catalunya',
				'thumbnail' => 'images/iesnautica.jpg',
				'external_url' => 'http://agora.xtec.cat/iesnautica/intranet/index.php?module=Pages&func=display&pageid=5',
				'parent_id' => '1',
				'lft' => '60',
				'rgt' => '71',
				'depth' => '1',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			35 => 
			array (
				'id' => '36',
				'name' => 'Institut Ramon Berenguer IV',
				'short_name' => 'iesramonberenguer',
				'description' => 'Cures auxiliars d’infermeria',
				'thumbnail' => 'images/iesramonberenguer.gif',
				'external_url' => 'http://www.iesramonberenguer.org/',
				'parent_id' => '1',
				'lft' => '72',
				'rgt' => '73',
				'depth' => '1',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			36 => 
			array (
				'id' => '37',
				'name' => 'Institut de Tecnificació',
				'short_name' => 'itecnificacio',
				'description' => 'Conducció d’activitats físicoesportives en el medinatural',
				'thumbnail' => 'images/itecnificacio.png',
				'external_url' => 'http://www.itecnificacio.cat/',
				'parent_id' => '1',
				'lft' => '74',
				'rgt' => '77',
				'depth' => '1',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			37 => 
			array (
				'id' => '38',
				'name' => 'Institut Montsià',
				'short_name' => 'iesmontsia',
			'description' => 'L’Institut Montsià és un centre públic d’Ensenyaments Professionals depenent del Departament d’Ensenyament on des del curs 12/13 s’imparteixen únicament ensenyaments oficials de Formació Professional Específica de GM, GS, CACS i PQPI (PTT i FIAP).',
				'thumbnail' => 'images/iesmontsia.gif',
				'external_url' => 'http://www.iesmontsia.org/estudis/',
				'parent_id' => '1',
				'lft' => '78',
				'rgt' => '97',
				'depth' => '1',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			38 => 
			array (
				'id' => '39',
				'name' => 'Institut Deltebre',
				'short_name' => 'iesdeltebre',
				'description' => 'Institut Deltebre',
				'thumbnail' => 'images/default_thumbnail.png',
				'external_url' => 'http://agora.xtec.cat/iesdeltebre/',
				'parent_id' => '1',
				'lft' => '98',
				'rgt' => '101',
				'depth' => '1',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			39 => 
			array (
				'id' => '40',
				'name' => 'Institut Flix',
				'short_name' => 'iesflix',
				'description' => 'L\'Institut de Flix és un centre de titularitat pública que depèn del DdE de la Generalitat de Catalunya. És el resultat de la fusió de l’Institut de Batxillerat de Flix i l’Escola Municipal de Formació Professional tot i que els seus inicis es remunten a ',
				'thumbnail' => 'images/iesflix.png',
				'external_url' => 'http://www.iesflix.cat/estudis',
				'parent_id' => '1',
				'lft' => '102',
				'rgt' => '107',
				'depth' => '1',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			40 => 
			array (
				'id' => '41',
				'name' => 'Institut Terra Alta',
				'short_name' => 'iesterraalta',
				'description' => '',
				'thumbnail' => 'images/iesterraalta.jpg',
				'external_url' => 'http://www.xtec.cat/iesterraalta/',
				'parent_id' => '1',
				'lft' => '108',
				'rgt' => '113',
				'depth' => '1',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			41 => 
			array (
				'id' => '42',
				'name' => 'Institut Julio Antonio',
				'short_name' => 'iesjulioantonio',
				'description' => 'L’any 1984 l’Institut d’FP adquireix autonomia pròpia en crear-se l’Institut de Formació Professional de Móra d’Ebre sota la direcció de Joan A. Escribà, anteriorment director delegat de l’extensió, que exercí aquest càrrec fins a la unificació dels dos c',
				'thumbnail' => 'images/default_thumbnail.png',
				'external_url' => 'http://iesjulioantonio.cat/?page_id=589',
				'parent_id' => '1',
				'lft' => '114',
				'rgt' => '123',
				'depth' => '1',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			42 => 
			array (
				'id' => '43',
				'name' => 'Institut Roquetes',
				'short_name' => 'institutroquetes',
				'description' => '',
				'thumbnail' => 'images/institutroquetes.jpg',
				'external_url' => 'http://www.institutroquetes.cat/?page_id=222',
				'parent_id' => '1',
				'lft' => '124',
				'rgt' => '129',
				'depth' => '1',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			43 => 
			array (
				'id' => '44',
				'name' => 'Institut La Sénia',
				'short_name' => 'ies-la-senia',
				'description' => '',
				'thumbnail' => 'images/es-la-senia.jpg',
				'external_url' => 'http://agora.xtec.cat/ies-la-senia/moodle/?lang=es',
				'parent_id' => '1',
				'lft' => '130',
				'rgt' => '133',
				'depth' => '1',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			44 => 
			array (
				'id' => '45',
				'name' => 'Institut Els Alfacs',
				'short_name' => 'insalfacs',
				'description' => '',
				'thumbnail' => 'images/default_thumbnail.png',
				'external_url' => 'http://moodle.insalfacs.cat/moodle/',
				'parent_id' => '1',
				'lft' => '134',
				'rgt' => '139',
				'depth' => '1',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			45 => 
			array (
				'id' => '46',
				'name' => 'Nuestra Señora de la Consolación',
				'short_name' => 'consolaciotortosa',
				'description' => 'Per tal de donar resposta al dret bàsic que tota persona té a l’educació, els Col·legis de la Consolació, inserits en la missió evangelitzadora de l’Església, proposem una alternativa educativa inspirada en l’Evangeli.És per això que el Caràcter Propi del',
				'thumbnail' => 'images/default_thumbnail.png',
				'external_url' => 'https://sites.google.com/a/xtec.cat/webconsolaciotortosa/',
				'parent_id' => '1',
				'lft' => '140',
				'rgt' => '145',
				'depth' => '1',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			46 => 
			array (
				'id' => '47',
				'name' => 'Institut Manuel Sales i Ferré',
				'short_name' => 'ies-manuel-sales',
				'description' => '',
				'thumbnail' => 'images/ies-manuel-sales.jpg',
				'external_url' => 'http://www.xtec.cat/ies-manuel-sales/portada.htm',
				'parent_id' => '1',
				'lft' => '146',
				'rgt' => '149',
				'depth' => '1',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			47 => 
			array (
				'id' => '48',
				'name' => 'Gestió administrativa',
				'short_name' => 'ges_admin',
				'description' => 'CICLE FORMATIU DE GRAU MITJÀ',
				'thumbnail' => 'images/Logo_03_admin_fin.png',
				'external_url' => 'http://www.xtec.cat/ies-manuel-sales/portada.htm',
				'parent_id' => '33',
				'lft' => '51',
				'rgt' => '52',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			48 => 
			array (
				'id' => '49',
				'name' => 'Manteniment electromecànic',
				'short_name' => 'ges_admin',
				'description' => 'CICLE FORMATIU DE GRAU MITJÀ',
				'thumbnail' => 'images/default_thumbnail.png',
				'external_url' => 'http://www.xtec.cat/ies-manuel-sales/portada.htm',
				'parent_id' => '33',
				'lft' => '53',
				'rgt' => '54',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			49 => 
			array (
				'id' => '50',
				'name' => 'Gestió administrativa',
				'short_name' => 'ges_admin',
				'description' => 'CICLE FORMATIU DE GRAU MITJÀ.',
				'thumbnail' => 'images/Logo_03_admin_fin.png',
				'external_url' => 'http://www.xtec.cat/centres/e3006976/INS/cicles_formatius.html',
				'parent_id' => '34',
				'lft' => '57',
				'rgt' => '58',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			50 => 
			array (
				'id' => '51',
				'name' => 'Navegació i pesca de litora',
				'short_name' => 'nav_pesca',
				'description' => 'CICLE FORMATIU DE GRAU MITJÀ',
				'thumbnail' => 'images/default_thumbnail.png',
				'external_url' => 'http://agora.xtec.cat/iesnautica/intranet/index.php?module=Pages&func=display&pageid=5',
				'parent_id' => '35',
				'lft' => '61',
				'rgt' => '62',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			51 => 
			array (
				'id' => '52',
				'name' => 'Manteniment i control de la maquinària de vaixells i embarcacions',
				'short_name' => 'nav_pesca',
				'description' => 'CICLE FORMATIU DE GRAU MITJÀ',
				'thumbnail' => 'images/default_thumbnail.png',
				'external_url' => 'http://agora.xtec.cat/iesnautica/intranet/index.php?module=Pages&func=display&pageid=5',
				'parent_id' => '35',
				'lft' => '63',
				'rgt' => '64',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			52 => 
			array (
				'id' => '53',
				'name' => 'Busseig a profunditat mitjana',
				'short_name' => 'nav_pesca',
				'description' => 'CICLE FORMATIU DE GRAU MITJÀ',
				'thumbnail' => 'images/default_thumbnail.png',
				'external_url' => 'http://agora.xtec.cat/iesnautica/intranet/index.php?module=Pages&func=display&pageid=5',
				'parent_id' => '35',
				'lft' => '65',
				'rgt' => '66',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			53 => 
			array (
				'id' => '54',
			'name' => 'Manteniment electromecànic (Manteniment vaixells d\'esbarjo)',
				'short_name' => 'nav_pesca',
				'description' => 'CICLE FORMATIU DE GRAU MITJÀ',
				'thumbnail' => 'images/default_thumbnail.png',
				'external_url' => 'http://agora.xtec.cat/iesnautica/intranet/index.php?module=Pages&func=display&pageid=5',
				'parent_id' => '35',
				'lft' => '67',
				'rgt' => '68',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			54 => 
			array (
				'id' => '55',
				'name' => 'Cures auxiliars d’infermeria',
				'short_name' => 'aux_enf',
				'description' => 'CICLE FORMATIU DE GRAU MITJÀ',
				'thumbnail' => 'images/logo_09_sanitat.png',
				'external_url' => '36',
				'parent_id' => '35',
				'lft' => '69',
				'rgt' => '70',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			55 => 
			array (
				'id' => '56',
				'name' => 'Conducció d’activitats físicoesportives en el medi natural',
				'short_name' => 'cond',
				'description' => 'CICLE FORMATIU DE GRAU MITJÀ',
				'thumbnail' => 'images/default_thumbnail.png',
				'external_url' => 'http://www.itecnificacio.cat',
				'parent_id' => '37',
				'lft' => '75',
				'rgt' => '76',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			56 => 
			array (
				'id' => '57',
				'name' => 'Gestió administrativa',
				'short_name' => 'ges_adm',
				'description' => 'CICLE FORMATIU DE GRAU MITJÀ',
				'thumbnail' => 'images/default_thumbnail.png',
				'external_url' => '',
				'parent_id' => '38',
				'lft' => '79',
				'rgt' => '80',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			57 => 
			array (
				'id' => '58',
			'name' => 'Gestió administrativa (àmbit jurídic)',
				'short_name' => 'juridic',
				'description' => 'CICLE FORMATIU DE GRAU MITJÀ',
				'thumbnail' => 'images/default_thumbnail.png',
				'external_url' => '',
				'parent_id' => '38',
				'lft' => '81',
				'rgt' => '82',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			58 => 
			array (
				'id' => '59',
				'name' => 'Comerç',
				'short_name' => 'comers',
				'description' => 'CICLE FORMATIU DE GRAU MITJÀ',
				'thumbnail' => 'images/default_thumbnail.png',
				'external_url' => '',
				'parent_id' => '38',
				'lft' => '83',
				'rgt' => '84',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			59 => 
			array (
				'id' => '60',
				'name' => 'Instal·lacions elèctriques i automàtiques',
				'short_name' => 'ins_elec',
				'description' => 'CICLE FORMATIU DE GRAU MITJÀ',
				'thumbnail' => 'images/default_thumbnail.png',
				'external_url' => '',
				'parent_id' => '38',
				'lft' => '85',
				'rgt' => '86',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			60 => 
			array (
				'id' => '61',
				'name' => 'Sistemes microinformàtics i xarxes',
				'short_name' => 'smx',
				'description' => 'CICLE FORMATIU DE GRAU MITJÀ',
				'thumbnail' => 'images/default_thumbnail.png',
				'external_url' => '',
				'parent_id' => '38',
				'lft' => '87',
				'rgt' => '88',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			61 => 
			array (
				'id' => '62',
				'name' => 'Electromecànica d’automòbils',
				'short_name' => 'elect_auto',
				'description' => 'CICLE FORMATIU DE GRAU MITJÀ',
				'thumbnail' => 'images/default_thumbnail.png',
				'external_url' => '',
				'parent_id' => '38',
				'lft' => '89',
				'rgt' => '90',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			62 => 
			array (
				'id' => '63',
				'name' => 'Carrosseria',
				'short_name' => 'corrosseria',
				'description' => 'CICLE FORMATIU DE GRAU MITJÀ',
				'thumbnail' => 'images/default_thumbnail.png',
				'external_url' => '',
				'parent_id' => '38',
				'lft' => '91',
				'rgt' => '92',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			63 => 
			array (
				'id' => '64',
				'name' => 'Atenció a persones en situació de dependència',
				'short_name' => 'aten_person',
				'description' => 'CICLE FORMATIU DE GRAU MITJÀ',
				'thumbnail' => 'images/default_thumbnail.png',
				'external_url' => '',
				'parent_id' => '38',
				'lft' => '93',
				'rgt' => '94',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			64 => 
			array (
				'id' => '65',
				'name' => 'Manteniment electromecànic',
				'short_name' => 'man_elec',
				'description' => 'CICLE FORMATIU DE GRAU MITJÀ',
				'thumbnail' => 'images/default_thumbnail.png',
				'external_url' => '',
				'parent_id' => '38',
				'lft' => '95',
				'rgt' => '96',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			65 => 
			array (
				'id' => '66',
				'name' => 'Atenció a persones en situació de dependència',
				'short_name' => 'nav_pesca',
				'description' => 'CICLE FORMATIU DE GRAU MITJÀ',
				'thumbnail' => 'images/default_thumbnail.png',
				'external_url' => '',
				'parent_id' => '42',
				'lft' => '115',
				'rgt' => '116',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			66 => 
			array (
				'id' => '67',
				'name' => 'Sistemes microinformàtics i xarxes',
				'short_name' => 'nav_pesca',
				'description' => 'CICLE FORMATIU DE GRAU MITJÀ',
				'thumbnail' => 'images/default_thumbnail.png',
				'external_url' => '',
				'parent_id' => '42',
				'lft' => '117',
				'rgt' => '118',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			67 => 
			array (
				'id' => '68',
				'name' => 'Gestió administrativa',
				'short_name' => 'ges_admin',
				'description' => 'CICLE FORMATIU DE GRAU MITJÀ',
				'thumbnail' => 'images/Logo_03_admin_fin.png',
				'external_url' => '',
				'parent_id' => '39',
				'lft' => '99',
				'rgt' => '100',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			68 => 
			array (
				'id' => '69',
				'name' => 'Gestió administrativa',
				'short_name' => 'ges_admin',
				'description' => 'CICLE FORMATIU DE GRAU MITJÀ',
				'thumbnail' => 'images/Logo_03_admin_fin.png',
				'external_url' => '',
				'parent_id' => '40',
				'lft' => '103',
				'rgt' => '104',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			69 => 
			array (
				'id' => '70',
				'name' => 'Manteniment electromecànic',
				'short_name' => 'ges_admin',
				'description' => 'CICLE FORMATIU DE GRAU MITJÀ',
				'thumbnail' => 'images/default_thumbnail.png',
				'external_url' => '',
				'parent_id' => '40',
				'lft' => '105',
				'rgt' => '106',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			70 => 
			array (
				'id' => '71',
				'name' => 'Gestió administrativa',
				'short_name' => 'ges_admin',
				'description' => 'CICLE FORMATIU DE GRAU MITJÀ',
				'thumbnail' => 'images/Logo_03_admin_fin.png',
				'external_url' => '',
				'parent_id' => '41',
				'lft' => '109',
				'rgt' => '110',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			71 => 
			array (
				'id' => '72',
				'name' => 'Manteniment electromecànic',
				'short_name' => 'ges_admin',
				'description' => 'CICLE FORMATIU DE GRAU MITJÀ',
				'thumbnail' => 'images/default_thumbnail.png',
				'external_url' => '',
				'parent_id' => '41',
				'lft' => '111',
				'rgt' => '112',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			72 => 
			array (
				'id' => '73',
				'name' => 'Gestió administrativa',
				'short_name' => 'ges_admin',
				'description' => 'CICLE FORMATIU DE GRAU MITJÀ',
				'thumbnail' => 'images/Logo_03_admin_fin.png',
				'external_url' => '',
				'parent_id' => '42',
				'lft' => '119',
				'rgt' => '120',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			73 => 
			array (
				'id' => '74',
				'name' => 'Electromecànica d’automòbils',
				'short_name' => 'elect_auto',
				'description' => 'CICLE FORMATIU DE GRAU MITJÀ',
				'thumbnail' => 'images/default_thumbnail.png',
				'external_url' => '',
				'parent_id' => '42',
				'lft' => '121',
				'rgt' => '122',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			74 => 
			array (
				'id' => '75',
				'name' => 'Perruqueria i cosmètica capilar',
				'short_name' => 'institutroquetes',
				'description' => 'CICLE FORMATIU DE GRAU MITJÀ',
				'thumbnail' => 'images/institutroquetes.jpg',
				'external_url' => 'http://www.institutroquetes.cat/?page_id=222',
				'parent_id' => '43',
				'lft' => '125',
				'rgt' => '126',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			75 => 
			array (
				'id' => '76',
				'name' => 'Estètica i bellesa ',
				'short_name' => 'institutroquetes',
				'description' => 'CICLE FORMATIU DE GRAU MITJÀ',
				'thumbnail' => 'images/institutroquetes.jpg',
				'external_url' => 'http://www.institutroquetes.cat/?page_id=222',
				'parent_id' => '43',
				'lft' => '127',
				'rgt' => '128',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			76 => 
			array (
				'id' => '77',
				'name' => 'Institut La Sénia',
				'short_name' => 'ies-la-senia',
				'description' => 'Gestió administrativa',
				'thumbnail' => 'images/es-la-senia.jpg',
				'external_url' => 'http://agora.xtec.cat/ies-la-senia/moodle/?lang=es',
				'parent_id' => '44',
				'lft' => '131',
				'rgt' => '132',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			77 => 
			array (
				'id' => '78',
				'name' => 'Gestió administrativa',
				'short_name' => 'insalfacs',
				'description' => 'CICLE FORMATIU DE GRAU MITJÀ',
				'thumbnail' => 'images/default_thumbnail.png',
				'external_url' => 'http://moodle.insalfacs.cat/moodle/',
				'parent_id' => '45',
				'lft' => '135',
				'rgt' => '136',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			78 => 
			array (
				'id' => '79',
				'name' => 'Cultius aqüícoles',
				'short_name' => 'insalfacs',
				'description' => 'CICLE FORMATIU DE GRAU MITJÀ',
				'thumbnail' => 'images/default_thumbnail.png',
				'external_url' => 'http://moodle.insalfacs.cat/moodle/',
				'parent_id' => '45',
				'lft' => '137',
				'rgt' => '138',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			79 => 
			array (
				'id' => '80',
				'name' => 'Cuina i gastronomia',
				'short_name' => 'bau',
				'description' => 'CICLE FORMATIU DE GRAU MITJÀ',
				'thumbnail' => 'images/LOGOBAU2.png',
				'external_url' => 'http://agora.xtec.cat/iesjbau/projecte-educatiu/estudis/',
				'parent_id' => '26',
				'lft' => '45',
				'rgt' => '46',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			80 => 
			array (
				'id' => '81',
				'name' => 'Serveis de restauració',
				'short_name' => 'bau',
				'description' => 'CICLE FORMATIU DE GRAU MITJÀ',
				'thumbnail' => 'images/LOGOBAU2.png',
				'external_url' => 'http://agora.xtec.cat/iesjbau/projecte-educatiu/estudis/',
				'parent_id' => '26',
				'lft' => '47',
				'rgt' => '48',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			81 => 
			array (
				'id' => '82',
				'name' => 'Cures auxiliars d’infermeria',
				'short_name' => 'consolaciotortosa',
				'description' => 'CICLE FORMATIU DE GRAU MITJÀ',
				'thumbnail' => 'images/default_thumbnail.png',
				'external_url' => 'https://sites.google.com/a/xtec.cat/webconsolaciotortosa/',
				'parent_id' => '46',
				'lft' => '141',
				'rgt' => '142',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			82 => 
			array (
				'id' => '83',
				'name' => 'Gestió administrativa',
				'short_name' => 'consolaciotortosa',
				'description' => 'CICLE FORMATIU DE GRAU MITJÀ',
				'thumbnail' => 'images/default_thumbnail.png',
				'external_url' => 'https://sites.google.com/a/xtec.cat/webconsolaciotortosa/',
				'parent_id' => '46',
				'lft' => '143',
				'rgt' => '144',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
			83 => 
			array (
				'id' => '84',
				'name' => 'Sistemes microinformàtics i xarxes',
				'short_name' => 'ies-manuel-sales',
				'description' => 'CICLE FORMATIU DE GRAU MITJÀ',
				'thumbnail' => 'images/ies-manuel-sales.jpg',
				'external_url' => 'http://www.xtec.cat/ies-manuel-sales/portada.htm',
				'parent_id' => '47',
				'lft' => '147',
				'rgt' => '148',
				'depth' => '2',
				'created_at' => $dateTime,
				'updated_at' => $dateTime,
				'deleted_at' => NULL,
				'created_by' => '0',
				'updated_by' => '0',
				'deleted_by' => '0',
			),
		));
	}

}
